version: '2'
services:
  # authdb:
  #   # image: 'mysql/mysql-server:latest'
  #   image: 'mcr.microsoft.com/mssql/server'
  #   # entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
  #   entrypoint: ['/opt/mssql/bin/sqlservr']
  #   ports:
  #     # - "3306:3306"
  #     - "1433:1433"
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=igQFUwjZZyxgken7gcKg*gTu
  #     # - MYSQL_DATABASE=auth
  #     # - MYSQL_USER=authUser
  #     # - MYSQL_PASSWORD=igQFUwjZZyxgken7gcKg*gTu
  #     # - MYSQL_ROOT_PASSWORD=igQFUwjZZyxgken7gcKg*gTu
  #     # - MYSQL_ROOT_HOST=*.*.*.*
  #   volumes:
  #     - auth-data:/var/opt/mssql
  #   networks:
  #     - authService
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      # - MONGODB_USERNAME=root
      - MONGODB_USERNAME=authService
      - MONGODB_PASSWORD=igQFUwjZZyxgken7gcKg*gTu
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_DATABASE=authdb
      # - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - authService
    volumes:
      - auth-data-mongodb:/bitnami
volumes:
  auth-data:
  auth-data-mongodb:
networks:
  authService:
