version: '2'
services:
  authdb:
    image: 'mysql/mysql-server:latest'
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_USER=authUser
      - MYSQL_PASSWORD=igQFUwjZZyxgken7gcKg*gTu
      - MYSQL_ROOT_PASSWORD=igQFUwjZZyxgken7gcKg*gTu
      - MYSQL_ROOT_HOST=*.*.*.*
    volumes:
      - auth-data:/var/lib/mysql
volumes:
  auth-data:
